addr: ':7700'
application: "YouVideo Core Service"
instance: "main"
cover_store: './data/covers'
ffmpeg_bin: 'ffmpeg'
ffprobe_bin: 'ffprobe'
datasource: "sqlite"
service:
  name: "YouVideoCoreService"
  display: "YouVideo Core Service"
sqlite:
  path: './data/database.db'
transcode:
  enable: false
  url: 'http://localhost:6700'
youplus:
  auth: false
  enablepath: false
  url: 'http://localhost:8999'
  enablerpc: false
  rpc: 'localhost:50055'
  entity:
    enable: false
    name: "youvideocore"
    version: 1
log:
  youlog:
    application: "YouVideo Core Service"
    instance: "main"
    addr: "localhost:50052"
    retry: 3000
    remote: false
youlibrary:
  enable: false
  url: "http://localhost:8000"
thumbnail:
  type: "thumbnailservice"
  service_url: "http://localhost:8020"
register:
  enable: false
  endpoints:
    - localhost:12379
  regpath: ./reg.yml
