addr: ':7700'
application: "YouVideo Core Service"
instance: "main"
cover_store: './static/covers'
ffmpeg_bin: 'ffmpeg'
ffprobe_bin: 'ffprobe'
transcode:
  enable: false
  url: 'http://localhost:6700'
auth:
  enable: true
  url: 'http://localhost:8999'
youlog:
  enable: true
  rpc_addr: "localhost:50052"