addr: ':7700'
application: "YouVideo Core Service"
instance: "main"
cover_store: './data/covers'
ffmpeg_bin: 'ffmpeg'
ffprobe_bin: 'ffprobe'
service:
  name: "YouVideoCoreService"
  display: "YouVideo Core Service"
datasource:
  sqlite:
    type: sqlite
    path: './data/database.db'
transcode:
  enable: false
  url: 'http://localhost:6700'
youplus:
  auth: false
  enablepath: false
  url: 'http://localhost:8999'
  enablerpc: false
  rpc: 'localhost:50055'
  entity:
    enable: false
    name: "youvideocore"
    version: 1
log:
  youlog:
    application: "YouVideo"
    instance: "main"
    engine:
      local:
        type: logrus
#      logservice:
#        type: youlogservice
#        address: "localhost:60376"
#      fluentd:
#        type: fluentd
#        url:  "http://localhost:53373"
youlibrary:
  enable: false
  url: "http://localhost:8000"
thumbnail:
  type: "local"
  service_url: "http://localhost:8020"
register:
  enable: false
  endpoints:
    - localhost:12379
  regpath: ./reg.yml
